update extract build reports step

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -119,22 +119,24 @@ jobs:
       - run:
           name: Extract build reports
           command: |
-            docker image ls
+            docker images
             docker ps -a
 
-            if `docker image inspect localstack/localstack` &> /dev/null; then
-              cid=$(docker create localstack/localstack)
+            if [[ "$(docker images -q mytest/mytest 2> /dev/null)" != "" ]]; then
+              echo "creating docker container for image"
+              cid=$(docker create mytest/mytest)
             else
+              echo "getting container from docker image"
               cid=$(docker ps -aq | head -n1)
             fi
 
             docker ps -a
             echo "extracting from ${cid}"
 
-            if [ ! -z ${cid} ]; then
-              docker cp ${cid}:/opt/code/localstack/nosetests.xml target/reports || true
-              docker cp ${cid}:/opt/code/localstack/.coverage target/ || true
-            fi
+            [[ "$cid" != "" ]] || { echo "could not create build container"; exit 1; }
+
+            docker cp ${cid}:/opt/code/localstack/nosetests.xml target/reports || true
+            docker cp ${cid}:/opt/code/localstack/.coverage target/ || true
           when: always
       - run:
           command: |
