Fix CircleCI workflow tracking (#10346)

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -29,7 +29,7 @@ commands:
             echo "export CI_JOB_URL=${CIRCLE_BUILD_URL}" >> $BASH_ENV
             # workflow ID as the job name to associate the tests with workflows in TB
             echo "export CI_JOB_NAME=${CIRCLE_WORKFLOW_ID}" >> $BASH_ENV
-            echo "export CI_JOB_ID=${CIRCLE_WORKFLOW_JOB_ID}" >> $BASH_ENV
+            echo "export CI_JOB_ID=${CIRCLE_JOB}" >> $BASH_ENV
             source $BASH_ENV
 
 jobs:
@@ -504,6 +504,27 @@ jobs:
             root: /tmp/workspace
             paths:
                 - repo/stats/
+  waiter:
+    executor: ubuntu-machine-amd64
+    working_directory: /tmp/workspace/repo
+    steps:
+      - run: |
+          while [[ $(curl --location --request GET "https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/job"| jq -r '.items[]|select(.name != "waiter" and .name != "push" and .name != "report")|.status' | grep -c "running") -gt 0 ]]; do
+              sleep 10
+            done
+          FAILED_COUNT=$(curl --location --request GET "https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/job" | jq -r '.items[]|.status' | grep -c "failed") || true
+          echo "failed count" $FAILED_COUNT
+          mkdir stats
+          if [[ $FAILED_COUNT -eq 0 ]]; then
+              echo "success" > stats/outcome.txt
+          else
+              echo "failure" > stats/outcome.txt
+          fi
+          cat stats/outcome.txt
+      - persist_to_workspace:
+            root: /tmp/workspace
+            paths:
+                - repo/stats/
   send-stats:
     executor: ubuntu-machine-amd64
     working_directory: /tmp/workspace/repo
@@ -511,22 +532,13 @@ jobs:
       - attach_workspace:
           at: /tmp/workspace
       - run:
-          when: on_fail
-          name: Detecting Job Status (FAIL)
-          command: |
-            echo "export CCI_STATUS='failure'" >> $BASH_ENV
-      - run:
-          when: on_success
-          name: Detecting Job Status (PASS)
-          command: |
-            echo "export CCI_STATUS='success'" >> $BASH_ENV
-      - run:
           when: always
           name: Load start time from file
           command: |
             START_TIME=$(cat stats/start-time.txt)
             END_TIME=$(date +%s)
-            echo '{"run_id": "'$CIRCLE_WORKFLOW_ID'", "start": '$START_TIME', "end": '$END_TIME', "commit": "'$CIRCLE_SHA1'", "branch": "'$CIRCLE_BRANCH'", "repository": "'$CIRCLE_PROJECT_USERNAME'/'$CIRCLE_PROJECT_REPONAME'", "outcome": "'$CCI_STATUS'"}' > stats/stats.json
+            OUTCOME=$(cat stats/outcome.txt)
+            echo '{"run_id": "'$CIRCLE_WORKFLOW_ID'", "start": '$START_TIME', "end": '$END_TIME', "commit": "'$CIRCLE_SHA1'", "branch": "'$CIRCLE_BRANCH'", "repository": "'$CIRCLE_PROJECT_USERNAME'/'$CIRCLE_PROJECT_REPONAME'", "outcome": "'$OUTCOME'"}' > stats/stats.json
             echo 'Sending: '$(cat stats/stats.json)
             curl -X POST "https://api.tinybird.co/v0/events?name=circle_ci_workflows" -H "Authorization: Bearer $TINYBIRD_CI_TOKEN" -d @stats/stats.json
 
@@ -535,10 +547,17 @@ jobs:
 workflows:
   main:
     jobs:
-      - save-start-time
-      - install:
+      - save-start-time:
+          filters:
+            branches:
+              only: master
+      - waiter:
           requires:
             - save-start-time
+      - send-stats:
+          requires:
+            - waiter
+      - install
       - preflight:
           requires:
             - install
@@ -595,19 +614,6 @@ workflows:
           requires:
             - docker-build-amd64
       - report:
-          requires:
-            - itest-sfn-legacy-provider
-            - itest-s3-v2-legacy-provider
-            - itest-cloudwatch-v2-provider
-            - acceptance-tests
-            - docker-test-amd64
-            - docker-test-arm64
-            - collect-not-implemented
-            - unit-tests
-      - send-stats:
-          filters:
-            branches:
-              only: master
           requires:
             - itest-sfn-legacy-provider
             - itest-s3-v2-legacy-provider
