Test out CircleCI workaround in simplified pipeline

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -505,16 +505,31 @@ jobs:
             paths:
                 - repo/stats/
   waiter:
-    docker:
-      - image: circleci/node
+    executor: ubuntu-machine-amd64
+    working_directory: /tmp/workspace/repo
     steps:
       - run: |
-          while [[ $(curl --location --request GET "https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/job"| jq -r '.items[]|select(.name != "waiter" and .name != "push")|.status' | grep -c "running") -gt 0 ]]
-            do
-              sleep 5
+          while [[ $(curl --location --request GET "https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/job"| jq -r '.items[]|select(.name != "waiter" and .name != "push")|.status' | grep -c "running") -gt 0 ]]; do
+              sleep 10
             done
-          curl --location --request GET "https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/job" --header "Circle-Token: $CCI_PROJECT_TOKEN"
-      - run: echo "All required jobs have now completed"
+          FAILED_COUNT=$(curl --location --request GET "https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/job" | jq -r '.items[]|.status' | grep -c "failed") || true
+          echo "failed count" $FAILED_COUNT
+          mkdir stats
+          if [[ $FAILED_COUNT -eq 0 ]]; then
+              echo "success" > stats/outcome.txt
+          else
+              echo "failure" > stats/outcome.txt
+          fi
+          cat stats/outcome.txt
+      - persist_to_workspace:
+            root: /tmp/workspace
+            paths:
+                - repo/stats/
+  failer:
+    executor: ubuntu-machine-amd64
+    working_directory: /tmp/workspace/repo
+    steps:
+      - run: exit 0
   send-stats:
     executor: ubuntu-machine-amd64
     working_directory: /tmp/workspace/repo
@@ -522,24 +537,15 @@ jobs:
       - attach_workspace:
           at: /tmp/workspace
       - run:
-          when: on_fail
-          name: Detecting Job Status (FAIL)
-          command: |
-            echo "export CCI_STATUS='failure'" >> $BASH_ENV
-      - run:
-          when: on_success
-          name: Detecting Job Status (PASS)
-          command: |
-            echo "export CCI_STATUS='success'" >> $BASH_ENV
-      - run:
           when: always
           name: Load start time from file
           command: |
             START_TIME=$(cat stats/start-time.txt)
             END_TIME=$(date +%s)
-            echo '{"run_id": "'$CIRCLE_WORKFLOW_ID'", "start": '$START_TIME', "end": '$END_TIME', "commit": "'$CIRCLE_SHA1'", "branch": "'$CIRCLE_BRANCH'", "repository": "'$CIRCLE_PROJECT_USERNAME'/'$CIRCLE_PROJECT_REPONAME'", "outcome": "'$CCI_STATUS'"}' > stats/stats.json
+            OUTCOME=$(cat stats/outcome.txt)
+            echo '{"run_id": "'$CIRCLE_WORKFLOW_ID'", "start": '$START_TIME', "end": '$END_TIME', "commit": "'$CIRCLE_SHA1'", "branch": "'$CIRCLE_BRANCH'", "repository": "'$CIRCLE_PROJECT_USERNAME'/'$CIRCLE_PROJECT_REPONAME'", "outcome": "'$OUTCOME'"}' > stats/stats.json
             echo 'Sending: '$(cat stats/stats.json)
-            curl -X POST "https://api.tinybird.co/v0/events?name=circle_ci_workflows" -H "Authorization: Bearer $TINYBIRD_CI_TOKEN" -d @stats/stats.json
+            curl -X POST "https://api.tinybird.co/v0/events?name=circle_ci_workflows_test" -H "Authorization: Bearer $TINYBIRD_CI_TOKEN" -d @stats/stats.json
 
 
 
@@ -550,89 +556,9 @@ workflows:
       - waiter:
           requires:
             - save-start-time
-      - install:
+      - failer:
           requires:
             - save-start-time
-      - preflight:
-          requires:
-            - install
-      - acceptance-tests:
-          requires:
-            - preflight
-      - itest-sfn-legacy-provider:
-          requires:
-            - preflight
-      - itest-s3-v2-legacy-provider:
-          requires:
-            - preflight
-      - itest-cloudwatch-v2-provider:
-          requires:
-            - preflight
-      - unit-tests:
-          requires:
-            - preflight
-      - docker-build:
-          name: docker-build-amd64
-          platform: amd64
-          machine_image: << pipeline.parameters.ubuntu-amd64-machine-image >>
-          resource_class: medium
-          requires:
-            - preflight
-      - docker-build:
-          name: docker-build-arm64
-          platform: arm64
-          # The latest version of ubuntu is not yet supported for ARM:
-          # https://circleci.com/docs/2.0/arm-resources/
-          machine_image: << pipeline.parameters.ubuntu-arm64-machine-image >>
-          resource_class: arm.medium
-          requires:
-            - preflight
-      - docker-test:
-          name: docker-test-arm64
-          platform: arm64
-          resource_class: arm.medium
-          machine_image: << pipeline.parameters.ubuntu-arm64-machine-image >>
-          requires:
-            - docker-build-arm64
-      - docker-test:
-          name: docker-test-amd64
-          platform: amd64
-          resource_class: medium
-          machine_image: << pipeline.parameters.ubuntu-amd64-machine-image >>
-          requires:
-            - docker-build-amd64
-      - bootstrap-tests:
-          requires:
-            - docker-build-amd64
-      - capture-not-implemented:
-          name: collect-not-implemented
-          requires:
-            - docker-build-amd64
-      - report:
-          requires:
-            - itest-sfn-legacy-provider
-            - itest-s3-v2-legacy-provider
-            - itest-cloudwatch-v2-provider
-            - acceptance-tests
-            - docker-test-amd64
-            - docker-test-arm64
-            - collect-not-implemented
-            - unit-tests
       - send-stats:
-          filters:
-            branches:
-              only: master
           requires:
             - waiter
-      - push:
-          filters:
-            branches:
-              only: master
-          requires:
-            - itest-sfn-legacy-provider
-            - itest-s3-v2-legacy-provider
-            - itest-cloudwatch-v2-provider
-            - acceptance-tests
-            - docker-test-amd64
-            - docker-test-arm64
-            - unit-tests
