rebasing PR

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -7,9 +7,12 @@ parameters:
   ubuntu-arm64-machine-image:
     type: string
     default: "ubuntu-2204:2023.02.1"
+  skip_test_selection:
+    type: boolean
+    default: false
   schedule-non-default-creds:
     type: string
-    default: "0 8 * * *"
+    default: "0 2 * * *"
 
 executors:
   ubuntu-machine-amd64:
@@ -19,6 +22,15 @@ executors:
 commands:
   prepare-pytest-tinybird:
     steps:
+      - unless:
+          condition: << pipeline.parameters.skip_test_selection >>
+          steps:
+            - run:
+                name: Setup test selection environment variable
+                command: |
+                  if [[ -n "$CI_PULL_REQUEST" ]] ; then
+                    echo "export TESTSELECTION_PYTEST_ARGS='--path-filter=target/testselection/test-selection.txt '" >> $BASH_ENV
+                  fi
       - run:
           name: Setup Environment Variables
           command: |
@@ -30,7 +42,6 @@ commands:
             else
               echo "export TINYBIRD_DATASOURCE=community_tests_circleci" >> $BASH_ENV
             fi
-            echo "export TINYBIRD_TOKEN=${TINYBIRD_CI_TOKEN}" >> $BASH_ENV
             echo "export TINYBIRD_TOKEN=${TINYBIRD_CI_TOKEN}" >> $BASH_ENV
             echo "export CI_COMMIT_BRANCH=${CIRCLE_BRANCH}" >> $BASH_ENV
             echo "export CI_COMMIT_SHA=${CIRCLE_SHA1}" >> $BASH_ENV
@@ -77,6 +88,36 @@ jobs:
           name: Checking AWS compatibility markers
           command: make check-aws-markers
 
+
+  # can't completely skip it since we need the dependency from other tasks => conditional in run step
+  test-selection:
+    executor: ubuntu-machine-amd64
+    working_directory: /tmp/workspace/repo
+    steps:
+      - attach_workspace:
+          at: /tmp/workspace
+      - unless:
+          condition: << pipeline.parameters.skip_test_selection >>
+          steps:
+            - run:
+                # script expects an environment variable $GITHUB_API_TOKEN to be set to fetch PR details
+                name: Generate test selection filters from changed files
+                command: |
+                  if [[ -z "$CI_PULL_REQUEST" ]] ; then
+                    echo "Skipping test selection"
+                    circleci-agent step halt
+                  else
+                    source .venv/bin/activate
+                    python -m localstack.testing.testselection.scripts.generate_test_selection_from_pr /tmp/workspace/repo $CI_PULL_REQUEST target/testselection/test-selection.txt
+                    cat target/testselection/test-selection.txt
+                  fi
+
+            - persist_to_workspace:
+                root:
+                  /tmp/workspace
+                paths:
+                  - repo/target/testselection/
+
   unit-tests:
     executor: ubuntu-machine-amd64
     working_directory: /tmp/workspace/repo
@@ -105,36 +146,6 @@ jobs:
             /tmp/workspace
           paths:
             - repo/target/coverage/
-
-  itest-sfn-legacy-provider:
-    executor: ubuntu-machine-amd64
-    working_directory: /tmp/workspace/repo
-    steps:
-      - attach_workspace:
-          at: /tmp/workspace
-      - prepare-pytest-tinybird
-      - run:
-          name: Test SFN Legacy provider
-          environment:
-            PROVIDER_OVERRIDE_STEPFUNCTIONS: "legacy"
-            TEST_PATH: "tests/aws/services/stepfunctions/legacy/"
-            COVERAGE_ARGS: "-p"
-          command: |
-            if [ -f aws_credentials.env ]; then
-              source aws_credentials.env
-            else
-              echo "aws_credentials.env file not found. Skipping setup of non-default aws credentials."
-            fi
-            COVERAGE_FILE="target/coverage/.coverage.sfnlegacy.${CIRCLE_NODE_INDEX}" \
-            PYTEST_ARGS="${TINYBIRD_PYTEST_ARGS}--reruns 3 --junitxml=target/reports/sfn_legacy.xml -o junit_suite_name='sfn_legacy'" \
-            make test-coverage
-      - persist_to_workspace:
-          root:
-            /tmp/workspace
-          paths:
-            - repo/target/coverage/
-      - store_test_results:
-          path: target/reports/
 
   acceptance-tests:
     executor: ubuntu-machine-amd64
@@ -168,6 +179,36 @@ jobs:
       - store_test_results:
           path: target/reports/
 
+  itest-sfn-legacy-provider:
+    executor: ubuntu-machine-amd64
+    working_directory: /tmp/workspace/repo
+    steps:
+      - attach_workspace:
+          at: /tmp/workspace
+      - prepare-pytest-tinybird
+      - run:
+          name: Test SFN Legacy provider
+          environment:
+            PROVIDER_OVERRIDE_STEPFUNCTIONS: "legacy"
+            TEST_PATH: "tests/aws/services/stepfunctions/legacy/"
+            COVERAGE_ARGS: "-p"
+          command: |
+            if [ -f aws_credentials.env ]; then
+              source aws_credentials.env
+            else
+              echo "aws_credentials.env file not found. Skipping setup of non-default aws credentials."
+            fi
+            COVERAGE_FILE="target/coverage/.coverage.sfnlegacy.${CIRCLE_NODE_INDEX}" \
+            PYTEST_ARGS="${TINYBIRD_PYTEST_ARGS}${TESTSELECTION_PYTEST_ARGS}--reruns 3 --junitxml=target/reports/sfn_legacy.xml -o junit_suite_name='sfn_legacy'" \
+            make test-coverage
+      - persist_to_workspace:
+          root:
+            /tmp/workspace
+          paths:
+            - repo/target/coverage/
+      - store_test_results:
+          path: target/reports/
+
   itest-s3-v2-legacy-provider:
     executor: ubuntu-machine-amd64
     working_directory: /tmp/workspace/repo
@@ -188,7 +229,7 @@ jobs:
               echo "aws_credentials.env file not found. Skipping setup of non-default aws credentials."
             fi
             COVERAGE_FILE="target/coverage/.coverage.s3legacy.${CIRCLE_NODE_INDEX}" \
-            PYTEST_ARGS="${TINYBIRD_PYTEST_ARGS}--reruns 3 --junitxml=target/reports/s3_legacy.xml -o junit_suite_name='s3_legacy'" \
+            PYTEST_ARGS="${TINYBIRD_PYTEST_ARGS}${TESTSELECTION_PYTEST_ARGS}--reruns 3 --junitxml=target/reports/s3_legacy.xml -o junit_suite_name='s3_legacy'" \
             make test-coverage
       - persist_to_workspace:
           root:
@@ -218,7 +259,7 @@ jobs:
               echo "aws_credentials.env file not found. Skipping setup of non-default aws credentials."
             fi
             COVERAGE_FILE="target/coverage/.coverage.cloudwatchV2.${CIRCLE_NODE_INDEX}" \
-            PYTEST_ARGS="${TINYBIRD_PYTEST_ARGS}--reruns 3 --junitxml=target/reports/cloudwatch_v2.xml -o junit_suite_name='cloudwatch_v2'" \
+            PYTEST_ARGS="${TINYBIRD_PYTEST_ARGS}${TESTSELECTION_PYTEST_ARGS}--reruns 3 --junitxml=target/reports/cloudwatch_v2.xml -o junit_suite_name='cloudwatch_v2'" \
             make test-coverage
       - persist_to_workspace:
           root:
@@ -255,14 +296,6 @@ jobs:
       - run:
           name: Save docker image
           command: PLATFORM="<< parameters.platform >>" make docker-save-image
-      - run:
-          name: Setup non-default AWS credentials
-          command: |
-              if [ -f aws_credentials.env ]; then
-                source aws_credentials.env
-              else
-                echo "aws_credentials.env file not found. Skipping setup of non-default aws credentials."
-              fi
       - persist_to_workspace:
           root:
             /tmp/workspace
@@ -315,19 +348,27 @@ jobs:
       - run:
           name: Run integration tests
           # circleci split returns newline separated list, so `tr` is necessary to prevent problems in the Makefile
+          # if we're doing performing a test selection, we need to filter the list of files before splitting by timings
           command: |
             if [ -f aws_credentials.env ]; then
               source aws_credentials.env
             else
               echo "aws_credentials.env file not found. Skipping setup of non-default aws credentials."
             fi
-            TEST_FILES=$(circleci tests glob "tests/aws/**/test_*.py" "tests/integration/**/test_*.py" | circleci tests split --split-by=timings | tr '\n' ' ')
-            PYTEST_ARGS="${TINYBIRD_PYTEST_ARGS}-o junit_family=legacy --junitxml=target/reports/test-report-<< parameters.platform >>-${CIRCLE_NODE_INDEX}.xml" \
+            if [ -z $TESTSELECTION_PYTEST_ARGS ] ; then
+              TEST_FILES=$(circleci tests glob "tests/aws/**/test_*.py" "tests/integration/**/test_*.py" | circleci tests split --verbose --split-by=timings | tr '\n' ' ')
+            else
+              TEST_FILES=$(circleci tests glob "tests/aws/**/test_*.py" "tests/integration/**/test_*.py" | python -m localstack.testing.testselection.scripts.filter_by_test_selection target/testselection/test-selection.txt | circleci tests split --verbose --split-by=timings | tr '\n' ' ')
+            fi
+            echo $TEST_FILES
+            PYTEST_ARGS="${TINYBIRD_PYTEST_ARGS}${TESTSELECTION_PYTEST_ARGS}-o junit_family=legacy --junitxml=target/reports/test-report-<< parameters.platform >>-${CIRCLE_NODE_INDEX}.xml" \
             COVERAGE_FILE="target/coverage/.coverage.<< parameters.platform >>.${CIRCLE_NODE_INDEX}" \
             TEST_PATH=$TEST_FILES \
             DEBUG=1 \
             make docker-run-tests
       - store_test_results:
+          path: target/reports/
+      - store_artifacts:
           path: target/reports/
       - persist_to_workspace:
           root:
@@ -412,7 +453,7 @@ jobs:
     working_directory: /tmp/workspace/repo
     steps:
       - attach_workspace:
-            at: /tmp/workspace
+          at: /tmp/workspace
       - run:
           name: Generate Random AWS Account ID
           command: |
@@ -432,12 +473,10 @@ jobs:
             echo "export TEST_AWS_REGION_NAME=${TEST_AWS_REGION_NAME}" >> aws_credentials.env
             echo "export TEST_AWS_ACCESS_KEY_ID=${TEST_AWS_ACCESS_KEY_ID}" >> aws_credentials.env
             echo "export TEST_AWS_ACCOUNT_ID=${TEST_AWS_ACCOUNT_ID}" >> aws_credentials.env
-
       - persist_to_workspace:
           root: /tmp/workspace
           paths:
             - repo/aws_credentials.env
-
 
   report:
     executor: ubuntu-machine-amd64
@@ -464,10 +503,14 @@ jobs:
       - run:
           name: Report coverage statistics
           command: |
-            source .venv/bin/activate
-            coverage report || true
-            coverage html || true
-            coveralls || true
+            if [ -z "${CI_PULL_REQUEST}" ]; then
+              source .venv/bin/activate
+              coverage report || true
+              coverage html || true
+              coveralls || true
+            else
+              echo "Skipping coverage reporting for pull request."
+            fi
       - run:
           name: store acceptance parity metrics
           command: |
@@ -645,18 +688,24 @@ workflows:
       - preflight:
           requires:
             - install
+      - test-selection:
+          requires:
+            - install
       - acceptance-tests:
           requires:
             - preflight
       - itest-sfn-legacy-provider:
           requires:
             - preflight
+            - test-selection
       - itest-s3-v2-legacy-provider:
           requires:
             - preflight
+            - test-selection
       - itest-cloudwatch-v2-provider:
           requires:
             - preflight
+            - test-selection
       - unit-tests:
           requires:
             - preflight
@@ -683,6 +732,7 @@ workflows:
           machine_image: << pipeline.parameters.ubuntu-arm64-machine-image >>
           requires:
             - docker-build-arm64
+            - test-selection
       - docker-test:
           name: docker-test-amd64
           platform: amd64
@@ -690,6 +740,7 @@ workflows:
           machine_image: << pipeline.parameters.ubuntu-amd64-machine-image >>
           requires:
             - docker-build-amd64
+            - test-selection
       - bootstrap-tests:
           requires:
             - docker-build-amd64
