fix dependencies installation before creating entrypoints for dev release

diff --git a/.github/workflows/aws-main.yml b/.github/workflows/aws-main.yml
--- a/.github/workflows/aws-main.yml
+++ b/.github/workflows/aws-main.yml
@@ -262,7 +262,7 @@ jobs:
           if git describe --exact-match --tags >/dev/null 2>&1; then
             echo "not publishing a dev release as this is a tagged commit"
           else
-            make install-basic publish || echo "dev release failed (maybe it is already published)"
+            make install-runtime publish || echo "dev release failed (maybe it is already published)"
           fi
 
   push-to-tinybird:
