Added step to create metric coverage diff and archive test artifacts

diff --git a/.github/workflows/aws-main.yml b/.github/workflows/aws-main.yml
--- a/.github/workflows/aws-main.yml
+++ b/.github/workflows/aws-main.yml
@@ -71,6 +71,8 @@ jobs:
   report:
     name: "Publish test results"
     runs-on: ubuntu-latest
+    needs:
+      - test
     steps:
         - name: Checkout
           uses: actions/checkout@v4
@@ -105,10 +107,51 @@ jobs:
 
         - name: Report coverage statistics
           run: |
-            python -m coverage report || true
-            python -m coverage html || true
+            coverage report || true
+            coverage html || true
             coveralls || true
 
+        - name: Create Coverage Diff (Code Coverage)
+          # pycobertura diff will return with exit code 0-3 -> we currently expect 2 (2: the changes worsened the overall coverage),
+          # but we still want cirecleci to continue with the tasks, so we return 0.
+          # From the docs:
+          # Upon exit, the diff command may return various exit codes:
+          #    0: all changes are covered, no new uncovered statements have been introduced
+          #    1: some exception occurred (likely due to inappropriate usage or a bug in pycobertura)
+          #    2: the changes worsened the overall coverage
+          #    3: the changes introduced uncovered statements but the overall coverage is still better than before
+          run: |
+            source .venv/bin/activate
+            pip install pycobertura
+            coverage xml --data-file=.coverage -o all.coverage.report.xml --include="localstack-core/localstack/services/*/**" --omit="*/**/__init__.py"
+            coverage xml --data-file=.coverage.acceptance -o acceptance.coverage.report.xml --include="localstack-core/localstack/services/*/**"  --omit="*/**/__init__.py"
+            pycobertura show --format html acceptance.coverage.report.xml -o coverage-acceptance.html
+            bash -c "pycobertura diff --format html all.coverage.report.xml acceptance.coverage.report.xml -o coverage-diff.html; if [[ \$? -eq 1 ]] ; then exit 1 ; else exit 0 ; fi"
+
+        - name: Create Metric Coverage Diff (API Coverage)
+          env:
+            COVERAGE_DIR_ALL: "parity_metrics"
+            COVERAGE_DIR_ACCEPTANCE: "acceptance_parity_metrics"
+            OUTPUT_DIR: "api-coverage"
+          run: |
+            source .venv/bin/activate
+            mkdir $OUTPUT_DIR
+            python -m scripts.metrics_coverage.diff_metrics_coverage
+
+        - name: Archive test artifacts
+          uses: actions/upload-artifact@v4
+          with:
+            name: coverage-and-parity-metrics
+            path: |
+              .coverage
+              api-coverage/
+              coverage-acceptance.html
+              coverage-diff.html
+              parity_metrics/
+              acceptance_parity_metrics/
+              scripts/implementation_coverage_aggregated.csv
+              scripts/implementation_coverage_full.csv
+            retention-days: 7
 
   push:
     name: "Push images"
